
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://root:dakck04gtnL3Q6aO173H@containers-us-west-101.railway.app:8003/railway
    username: root
    password: dakck04gtnL3Q6aO173H
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
      #springdoc:
      #  pathsToMatch:
      #    - /auth/**
      #  swagger-ui:
      #    use-root-path: true

      #server:
      # servlet:
      #   contextPath: /alunoOnline